/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    obras: Obra;
    categorias: Categoria;
    itens: Iten;
    'estoque-obra': EstoqueObra;
    movimentacoes: Movimentacoe;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    obras: ObrasSelect<false> | ObrasSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    itens: ItensSelect<false> | ItensSelect<true>;
    'estoque-obra': EstoqueObraSelect<false> | EstoqueObraSelect<true>;
    movimentacoes: MovimentacoesSelect<false> | MovimentacoesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cadastro de obras e canteiros de construção civil
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "obras".
 */
export interface Obra {
  id: string;
  /**
   * Ex: Residencial Vista do Parque, Edifício Corporativo Alpha
   */
  nome: string;
  /**
   * URL amigável para a página pública (ex: residencial-vista-do-parque)
   */
  slug: string;
  /**
   * Código interno (ex: OBR-001, EMP-2026)
   */
  codigo: string;
  status: 'planejamento' | 'em_andamento' | 'pausada' | 'concluida';
  responsavel: string;
  contatoResponsavel?: string | null;
  emailContato?: string | null;
  endereco?: {
    logradouro?: string | null;
    numero?: string | null;
    bairro?: string | null;
    cidade?: string | null;
    estado?: string | null;
    cep?: string | null;
  };
  dataInicio?: string | null;
  previsaoTermino?: string | null;
  foto?: (string | null) | Media;
  fotoUrl?: string | null;
  /**
   * Se desmarcado, a página pública desta obra ficará inacessível
   */
  publicaAtiva?: boolean | null;
  /**
   * Se marcado, os custos unitários e totais serão visíveis na página pública
   */
  exibirValores?: boolean | null;
  descricao?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Imagens de materiais, canteiros de obra e comprovantes de entrega
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Categorias de materiais, insumos, ferramentas e EPIs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: string;
  nome: string;
  /**
   * Ex: alvenaria, ferramentas-eletricas, epis, hidraulica
   */
  slug: string;
  tipo: 'material' | 'ferramenta' | 'epi' | 'geral';
  cor?: ('blue' | 'amber' | 'emerald' | 'purple' | 'rose' | 'slate') | null;
  descricao?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catálogo de materiais, insumos, ferramentas e EPIs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itens".
 */
export interface Iten {
  id: string;
  /**
   * Ex: Cimento CP-II 50kg, Furadeira de Impacto Bosch GSB 13 RE
   */
  nome: string;
  /**
   * Código único para identificação rápida no almoxarifado
   */
  codigo: string;
  tipo: 'material_consumivel' | 'ferramenta_equipamento' | 'epi_seguranca';
  categoria: string | Categoria;
  unidade:
    'un' | 'saco' | 'barra' | 'rolo' | 'cx' | 'pct' | 'kg' | 'ton' | 'm' | 'm2' | 'm3' | 'litro' | 'galao' | 'par';
  /**
   * Quantidade mínima recomendada para gerar alerta de reposição
   */
  estoqueMinimoPadrao?: number | null;
  foto?: (string | null) | Media;
  /**
   * URL externa de imagem caso não faça upload de arquivo
   */
  fotoUrl?: string | null;
  marca?: string | null;
  /**
   * Identificador único da ferramenta física
   */
  numeroPatrimonio?: string | null;
  estadoConservacao?: ('novo' | 'otimo' | 'bom' | 'em_manutencao' | 'danificado') | null;
  custoUnitario?: number | null;
  especificacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Saldo e localização de cada material/ferramenta em cada canteiro de obras
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estoque-obra".
 */
export interface EstoqueObra {
  id: string;
  obra: string | Obra;
  item: string | Iten;
  /**
   * Saldo físico atual disponível no almoxarifado
   */
  quantidade: number;
  /**
   * Gera alerta visual quando saldo for menor ou igual
   */
  estoqueMinimo?: number | null;
  /**
   * Ferramentas retiradas temporariamente por operários
   */
  quantidadeEmprestada?: number | null;
  /**
   * Ex: Container 1 - Prateleira A, Galpão Central, Pátio Areia
   */
  localizacao?: string | null;
  ultimaMovimentacao?: string | null;
  observacoes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Registro de entradas, saídas, empréstimos e devoluções no almoxarifado
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movimentacoes".
 */
export interface Movimentacoe {
  id: string;
  obra: string | Obra;
  item: string | Iten;
  tipo:
    | 'entrada'
    | 'saida'
    | 'emprestimo_ferramenta'
    | 'devolucao_ferramenta'
    | 'ajuste_inventario'
    | 'transferencia_saida'
    | 'transferencia_entrada';
  quantidade: number;
  dataHora: string;
  /**
   * Nome do colaborador ou empreiteiro que retirou
   */
  solicitante?: string | null;
  /**
   * Ex: Torre B - 4º Pavimento, Fundação, Elétrica Térreo
   */
  frenteServico?: string | null;
  documentoReferencia?: string | null;
  comprovante?: (string | null) | Media;
  observacoes?: string | null;
  registradoPor?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'engenheiro' | 'almoxarife' | 'visualizador';
  /**
   * Deixe vazio para dar acesso a todas as obras
   */
  obrasPermitidas?: (string | Obra)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'obras';
        value: string | Obra;
      } | null)
    | ({
        relationTo: 'categorias';
        value: string | Categoria;
      } | null)
    | ({
        relationTo: 'itens';
        value: string | Iten;
      } | null)
    | ({
        relationTo: 'estoque-obra';
        value: string | EstoqueObra;
      } | null)
    | ({
        relationTo: 'movimentacoes';
        value: string | Movimentacoe;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "obras_select".
 */
export interface ObrasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  codigo?: T;
  status?: T;
  responsavel?: T;
  contatoResponsavel?: T;
  emailContato?: T;
  endereco?:
    | T
    | {
        logradouro?: T;
        numero?: T;
        bairro?: T;
        cidade?: T;
        estado?: T;
        cep?: T;
      };
  dataInicio?: T;
  previsaoTermino?: T;
  foto?: T;
  fotoUrl?: T;
  publicaAtiva?: T;
  exibirValores?: T;
  descricao?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  tipo?: T;
  cor?: T;
  descricao?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "itens_select".
 */
export interface ItensSelect<T extends boolean = true> {
  nome?: T;
  codigo?: T;
  tipo?: T;
  categoria?: T;
  unidade?: T;
  estoqueMinimoPadrao?: T;
  foto?: T;
  fotoUrl?: T;
  marca?: T;
  numeroPatrimonio?: T;
  estadoConservacao?: T;
  custoUnitario?: T;
  especificacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "estoque-obra_select".
 */
export interface EstoqueObraSelect<T extends boolean = true> {
  obra?: T;
  item?: T;
  quantidade?: T;
  estoqueMinimo?: T;
  quantidadeEmprestada?: T;
  localizacao?: T;
  ultimaMovimentacao?: T;
  observacoes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "movimentacoes_select".
 */
export interface MovimentacoesSelect<T extends boolean = true> {
  obra?: T;
  item?: T;
  tipo?: T;
  quantidade?: T;
  dataHora?: T;
  solicitante?: T;
  frenteServico?: T;
  documentoReferencia?: T;
  comprovante?: T;
  observacoes?: T;
  registradoPor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  obrasPermitidas?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}